version: '3.7'
services:
  sbe_user_build:
    container_name: sbe_user
    build:
      context: ../
      dockerfile: docker/DockerfileBuild
    environment:
      LOCAL_DEV: 'true'
      RDS_DB_HOST: sbehost
      RDS_DB_PORT: 5432
      RDS_DB_USER: postgres
      RDS_DB_PASSWORD: mysecretpassword
      RDS_DB_NAME: sbe
      SONARQUBE_SERVER: http://sonarqube:9000
  sbe-user-deploy:
    container_name: sbe_user
    build:
      context: ../
      dockerfile: docker/DockerfileDeploy
    ports:
      - 7730:8080
    environment:
      LOCAL_DEV: 'true'
      RDS_DB_HOST: sbehost
      RDS_DB_PORT: 5432
      RDS_DB_USER: postgres
      RDS_DB_PASSWORD: mysecretpassword
      RDS_DB_NAME: sbe
      UI_URL: http://sbe_ui_deploy:8080
      AUTH_URL: http://sbe-oauth-deploy:8080/oauth/token
networks:
  default:
    external:
      name: sbe-network
