apiVersion: v1
kind: Template
metadata:
  name: user-service-pipeline-template
  annotations:
    openshift.io/display-name: USER SERVICE PIPELINE
    description: USER SVC PIPELINE
    iconClass: "icon-java"
    tags: "java"
    template.openshift.io/bindable: "false"
parameters:
  - name: APP_NAME
    description: The name assigned to all of the application objects defined in this template.
    displayName: Application Name
    required: true
    value: user-service
  - name: SOURCE_REPOSITORY_URL
    displayName: Source Repository URL
    description: The URL of the repository with your application source code
    value: git@github.com:Acuity-Inc/spider-root.git
    required: true
  - name: SOURCE_REPOSITORY_SECRET_KEY
    description: Number of replicas to run
    value: gitsshkey
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: Github branch to deploy
    value: develop
  - name: ENVIRONMENT
    description: The application environment.
    displayName: Application Environment
    required: true
    value: nonprod
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${ENVIRONMENT}-${APP_NAME}-pipeline
    spec:
      runPolicy: SerialLatestOnly
      source:
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        sourceSecret:
          name: ${SOURCE_REPOSITORY_SECRET_KEY}
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: Backend/user_service/Jenkinsfile-${ENVIRONMENT}
labels:
  name: ${APP_NAME}-pipeline
